/**
 * One-off helper for the Block 6 final report — computes FULL-HISTORY
 * (not just last-25-months) metrics for RS3M and all 3 benchmarks, reusing
 * the exact same series already generated by analyze-candidate.ts
 * (re-fetched here identically) and the same tested portfolio-metrics.ts
 * functions. Not part of the audit pipeline itself — just a convenience
 * script to populate the final report's full-history table accurately
 * instead of hand-computing it.
 */
import { setupSandboxIO } from "../lib/sandbox-io";
setupSandboxIO();

import { fetchRs3mUniverse, RS3M_BENCHMARK, RS3M_UNIVERSE } from "./lib/fetch-candidate-assets";
import { runRelativeStrengthBacktest, type RelativeStrengthAssetInput } from "@/core/backtesting/research/relative-strength";
import { computeBuyAndHoldMonthlyReturns, computeEqualWeightBuyAndHoldMonthlyReturns } from "@/core/backtesting/research/benchmarks";
import { computeMonthlyReturnMetrics } from "@/core/backtesting/research/portfolio-metrics";
import { RS3M_CANDIDATE_V1 } from "@/core/paper-trading/rs3m/candidate";

async function main() {
  const byMarket = await fetchRs3mUniverse("all", RS3M_CANDIDATE_V1.datasetFrom);
  if (!byMarket) {
    console.error("fetch failed");
    process.exitCode = 1;
    return;
  }

  const config = { lookbackMonths: RS3M_CANDIDATE_V1.lookbackMonths, benchmarkMarket: RS3M_BENCHMARK, rebalanceCostBps: RS3M_CANDIDATE_V1.referenceRebalanceCostBps };
  const assetInputs: RelativeStrengthAssetInput[] = RS3M_UNIVERSE.map((market) => ({ market, candles: byMarket.get(market)! }));
  const engineResult = runRelativeStrengthBacktest(assetInputs, config);

  const months = engineResult.periods.map((p) => p.holdMonth);
  const decisionAndHoldMonths = [engineResult.periods[0]?.decisionMonth, ...months].filter((m): m is string => m !== undefined);

  const spyAsset = { market: RS3M_BENCHMARK, candles: byMarket.get(RS3M_BENCHMARK)! };
  const universeAssets = RS3M_UNIVERSE.map((m) => ({ market: m, candles: byMarket.get(m)! }));
  const spyBuyAndHoldMonthly = computeBuyAndHoldMonthlyReturns(spyAsset, decisionAndHoldMonths);
  const ewBuyAndHoldStaticMonthly = computeEqualWeightBuyAndHoldMonthlyReturns(universeAssets, decisionAndHoldMonths);
  const ewRebalancedMonthly = engineResult.equalWeightEquityCurve.map((pt, i) => {
    const prevEquity = i === 0 ? 1 : engineResult.equalWeightEquityCurve[i - 1].equity;
    return prevEquity > 0 ? ((pt.equity - prevEquity) / prevEquity) * 100 : 0;
  });
  const rs3mMonthly = engineResult.periods.map((p) => p.periodReturnPct);

  console.log("RS3M full-history:", JSON.stringify(computeMonthlyReturnMetrics(rs3mMonthly), null, 2));
  console.log("SPY Buy&Hold full-history:", JSON.stringify(computeMonthlyReturnMetrics(spyBuyAndHoldMonthly), null, 2));
  console.log("EW Buy&Hold static full-history:", JSON.stringify(computeMonthlyReturnMetrics(ewBuyAndHoldStaticMonthly), null, 2));
  console.log("EW Rebalanced full-history:", JSON.stringify(computeMonthlyReturnMetrics(ewRebalancedMonthly), null, 2));
}

main().catch((e) => {
  console.error(e);
  process.exitCode = 1;
});
